ユーザー名自動取得化
P-nutsK/Scratch-Last-login pull request #1
Opened 2022-10-18 04:18 UTC by arch-herobrine

適当に作ってみました。chromeのfetchとしてコピーを使ってるんで無駄に長くなっていますがそれはいずれ修正します()

2022-10-18 06:19 UTC, arch-herobrine commented
一応無駄に長くなったのを修正。

2022-10-18 23:17 UTC, arch-herobrine commented
すいませんミスって一回閉じました

2022-10-20 07:32 UTC, P-nutsK requested changes
ありがとうございます
```js
(await (await fetch("https://scratch.mit.edu/session/", {"headers": {"x-requested-with": "XMLHttpRequest"}})).json()).user.username
```
`await`を使うならこんな感じがいいと思います

2022-10-22 01:08 UTC, arch-herobrine commented
早速やってみます。

2022-10-22 01:23 UTC, arch-herobrine commented
出来ました。一応組み込んでみて動いたんで適用しました。

2022-10-29 03:56 UTC, merged